### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by lbmn** [unicredit/cello#1]
One of Nim's top advocacy points is the degree to which it and its module ecosystem is [copyfree](http://copyfree.org/standard/) - anyone can use it for whatever purpose without becoming subjected to pages and pages of legal threats that no one *really* understands...

Nim uses the [MIT license](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html) for all of its compiler, stdlib, and tooling - and that is also what nimble recommends as the default for new modules.   Over 87% of nimble modules currently fit the copyfree standard, higher than any other programming language that Nim competes with.

Your module [currently](https://archive.is/dUwt1) uses the Apache License, which is [not considered free by copyfree.org](http://copyfree.org/standard/rejected): 

* Section 4, subsections 2 and 4 of the Apache License 2.0 violate point 3 (Free Modification and Derivation) of the Copyfree Standard Definition by specifying conditions (beyond licensing) that must apply to modifications.

People who care about genuine software freedom are looking to Nim for many long-term project ideas (ex. BSD Unix with Nim userland), but we will exclude any components that aren't copyfree (or have dependencies that aren't copyfree).

What are your reasons for using the AL2?  Why not use [a copyfree license](http://copyfree.org/standard/licenses)  like MIT instead?

**Comment by andreaferretti** [comment]
There's no license problem. The Apache 2 License is a perfectly valid and useful license,.

**Comment by lbmn** [comment]
I agree that AL2 is "a perfectly valid and useful license" that is used in many AL2-licensed ecosystems.  But it is [unnecessarily complicated](http://univacc.net/pragmatic/license_simplicity_2), restrictive, and there indeed is a problem using it in copyfree ecosystems like [OpenBSD](https://www.openbsd.org/policy.html) [[2]](http://softwareengineering.stackexchange.com/questions/263227/why-are-apache-2-0-works-excluded-from-openbsd) and Nim.

You are free to use whatever license you want for the software you write.  However using AL2 will have the following consequences:

* Making Nim more popular would be good for all developers who use Nim.  Nim's market share is still very small, and it could use all the advocacy points it can get.   Out of hundreds of programming languages out there, Nim isn't the fastest, highest paying, most stable, etc.  But there's one category at which Nim scores NUMBER ONE, and that's license freedom.  (Runner-ups among viable languages are Haskell and Lua, which don't compete with Nim directly.)  Using non-copyfree licenses would undermine Nim's claim as the most unencumbered legalese-free programming language ecosystem.

* If you write a module that would be a good addition to the Nim standard library, your code cannot be used.

* Your module and everything that depends on it will be excluded from our future Copyfree Unix projects.

* Someone else will have to reinvent the wheel, writing an alternative genuinely free Succinct Data Structure module for Nim, while being fearful of writing code that is too similar to yours...

* Many people will see your otherwise-great contributions as nothing but harmful pollution and ostracize you.

**Comment by andreaferretti** [comment]
I am sorry I have been harsh, but this is [not the first time](https://github.com/andreaferretti/rosencrantz/issues/9) you open such an issue on a library I have written. I am perfectly fine with the terms of the Apache2 license - I think it is permissive enough by any reasonable standard, so I am not planning to change it.
